# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f874c5d036f8d62351b36103441770fc50be58604789952e23a1bf31dad59bd6a95600f9bd7373db4ae5054664253f87a4a5877c68274e205770f35bbbcf4a6a

test:
  secret_key_base: 4f7c8f17d3fa3e0a030ef742783b2902a7b9c27f70ec895193d3086baf912538a2757bed4d0b58119d747aa9678326d3ce88f24447ee5e968ea52b0dfc3007cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
